todo.app.version=${project.version}
todo.app.default-theme=light
todo.app.default-schedule-card-style=Classic
todo.db.mode=sqlite
todo.db.driver=org.sqlite.JDBC
todo.db.url=
todo.db.user=
todo.db.password=
todo.app.data-dir=
todo.db.sqlite.path=
